"""Structural tests over the generated complex-table / complex-list fixtures.

These complement the YAML-driven cases with assertions the YAML framework
cannot express (multi-chunk splitting, no-row-lost invariants, cross-chunk
header repetition). Fixtures are generated by data/unittests/generate_fixtures.py.

Assertions are structural on purpose: content presence, heading preservation
and metadata contracts rather than exact chunk counts, so that legitimate
changes to the chunk-size strategy do not break them.
"""

from pathlib import Path

import pytest

from docchunker import DocChunker

UNITTEST_DATA_DIR = Path(__file__).parent.parent / "data" / "unittests"
COMPLEX_TABLES = UNITTEST_DATA_DIR / "complex_tables.docx"
COMPLEX_LISTS = UNITTEST_DATA_DIR / "complex_lists.docx"


@pytest.fixture(scope="module")
def table_chunks():
    if not COMPLEX_TABLES.exists():
        pytest.skip(f"Fixture not found: {COMPLEX_TABLES}")
    return DocChunker(chunk_size=1000).process_document(str(COMPLEX_TABLES))


@pytest.fixture(scope="module")
def list_chunks():
    if not COMPLEX_LISTS.exists():
        pytest.skip(f"Fixture not found: {COMPLEX_LISTS}")
    return DocChunker(chunk_size=1000).process_document(str(COMPLEX_LISTS))


class TestLargeTableSplitting:
    def test_large_table_produces_multiple_chunks(self, table_chunks):
        catalog_chunks = [
            c for c in table_chunks
            if c.metadata["node_type"] == "table_rows"
            and "Large Product Catalog" in c.metadata["headings"]
        ]
        assert len(catalog_chunks) >= 2, \
            "A 30-row table should not fit in a single 1000-char chunk"

    def test_no_row_is_lost_across_chunks(self, table_chunks):
        combined = "\n".join(c.text for c in table_chunks)
        for i in range(1, 31):
            assert f"Gadget model {i:02d}" in combined, f"Row {i} missing from output"

    def test_header_repeated_in_every_table_chunk(self, table_chunks):
        catalog_chunks = [
            c for c in table_chunks
            if c.metadata["node_type"] == "table_rows"
            and "Large Product Catalog" in c.metadata["headings"]
        ]
        for chunk in catalog_chunks:
            assert "Product Name:" in chunk.text
            assert "Description:" in chunk.text
            assert "Price:" in chunk.text

    def test_heading_context_repeated_in_every_table_chunk(self, table_chunks):
        catalog_chunks = [
            c for c in table_chunks
            if c.metadata["node_type"] == "table_rows"
            and "Large Product Catalog" in c.metadata["headings"]
        ]
        for chunk in catalog_chunks:
            assert "Large Product Catalog" in chunk.text
            assert "Complex Tables Test Document" in chunk.text


class TestMergedCellsTable:
    def test_vertically_merged_cell_text_appears_in_each_spanned_row(self, table_chunks):
        merged_chunks = [c for c in table_chunks if "EMEA shared region" in c.text]
        assert merged_chunks, "Merged-cell table content not found"
        # The merged region label spans two data rows, so it appears at least twice.
        assert any(c.text.count("EMEA shared region") >= 2 for c in merged_chunks)

    def test_horizontally_merged_row_is_present(self, table_chunks):
        assert any(
            "Full year summary spanning all quarter columns" in c.text
            for c in table_chunks
        )


class TestWideTable:
    def test_wide_row_keeps_all_twelve_columns_together(self, table_chunks):
        wide_chunks = [c for c in table_chunks if "wide-r1-c01" in c.text]
        assert wide_chunks, "Wide table content not found"
        chunk = wide_chunks[0]
        for col in range(1, 13):
            assert f"wide-r1-c{col:02d}" in chunk.text, \
                f"Column {col} separated from its row"
            assert f"Metric{col:02d}" in chunk.text


class TestHeaderOnlyTable:
    def test_header_only_table_emits_dedicated_chunk(self, table_chunks):
        header_chunks = [
            c for c in table_chunks
            if c.metadata["node_type"] == "table_header_only"
        ]
        assert len(header_chunks) == 1
        assert "Status Code" in header_chunks[0].text
        assert "Header Only Table" in header_chunks[0].metadata["headings"]


class TestDeeplyNestedLists:
    def test_all_five_levels_stay_in_one_chunk(self, list_chunks):
        deep_chunks = [c for c in list_chunks if "Whitelist monitoring agents level five" in c.text]
        assert deep_chunks, "Deepest list level not found in any chunk"
        chunk = deep_chunks[0]
        for text in (
            "Deploy platform level one",
            "Provision infrastructure level two",
            "Configure network level three",
            "Open firewall ports level four",
        ):
            assert text in chunk.text, f"Ancestor item missing: {text}"

    def test_nesting_depth_reflected_by_increasing_indentation(self, list_chunks):
        deep_chunks = [c for c in list_chunks if "Whitelist monitoring agents level five" in c.text]
        chunk = deep_chunks[0]
        lines = {
            level: next(l for l in chunk.text.splitlines() if marker in l)
            for level, marker in enumerate([
                "Deploy platform level one",
                "Provision infrastructure level two",
                "Configure network level three",
                "Open firewall ports level four",
                "Whitelist monitoring agents level five",
            ])
        }
        indents = [len(line) - len(line.lstrip()) for line in lines.values()]
        assert indents == sorted(indents), "Indentation should not decrease with depth"
        assert indents[-1] > indents[0], "Deepest level should be indented more than the first"


class TestMixedLists:
    def test_numbered_list_and_substeps_stay_together(self, list_chunks):
        chunks = [c for c in list_chunks if "Numbered step alpha" in c.text]
        assert chunks
        assert "Numbered substep alpha-one: interview users" in chunks[0].text
        assert "Numbered substep alpha-two: draft specification" in chunks[0].text

    def test_style_based_bullets_detected_as_list(self, list_chunks):
        chunks = [c for c in list_chunks if "Bullet term latency" in c.text]
        assert chunks, "Style-based bullet items not found"
        assert all(c.metadata["node_type"] == "list_container" for c in chunks)


class TestInterruptedList:
    def test_all_items_and_interruption_survive(self, list_chunks):
        combined = "\n".join(c.text for c in list_chunks)
        for text in (
            "Interrupted item one",
            "Interrupted item two",
            "Warning interlude",
            "Interrupted item three",
            "Interrupted item four",
        ):
            assert text in combined

    def test_interruption_keeps_section_heading_context(self, list_chunks):
        warning_chunks = [c for c in list_chunks if "Warning interlude" in c.text]
        assert warning_chunks
        for chunk in warning_chunks:
            assert "Interrupted List" in chunk.metadata["headings"]


class TestListAfterTable:
    def test_table_and_following_list_share_heading_context(self, list_chunks):
        table_part = [
            c for c in list_chunks
            if "Flour for the base" in c.text and c.metadata["node_type"] == "table_rows"
        ]
        list_part = [
            c for c in list_chunks
            if "After-table step one" in c.text and c.metadata["node_type"] == "list_container"
        ]
        assert table_part, "Table before list not chunked as table_rows"
        assert list_part, "List after table not chunked as list_container"
        assert "List After Table" in table_part[0].metadata["headings"]
        assert "List After Table" in list_part[0].metadata["headings"]

    def test_list_after_table_keeps_all_items_together(self, list_chunks):
        chunks = [c for c in list_chunks if "After-table step one" in c.text]
        assert "After-table step two" in chunks[0].text
        assert "After-table step three" in chunks[0].text


class TestFixtureWideInvariants:
    @pytest.mark.parametrize("fixture_name", ["table_chunks", "list_chunks"])
    def test_no_empty_chunks_and_metadata_contract(self, fixture_name, request):
        chunks = request.getfixturevalue(fixture_name)
        assert chunks
        for chunk in chunks:
            assert chunk.text.strip(), "Empty chunk produced"
            for key in ("document_id", "source_type", "node_type", "headings", "num_chars"):
                assert key in chunk.metadata
            assert chunk.metadata["source_type"] == "docx"
